version: '3'
services:
  bot:
    image: bot
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - API_URL=${API_URL}
    build:
      context: bot
      args:
        - DOCKER_BUILDKIT=1
      dockerfile: Dockerfile
    ports:
      - 8001:8001
  ai_chat:
    image: ai_chat
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SERPAPI_API_KEY=${SERPAPI_API_KEY}
    build:
      context: ai_chat
      args:
        - DOCKER_BUILDKIT=1
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/app
