version: '3'
services:
  ai_chat:
    image: ai_chat
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    build:
      context: ai_chat
      args:
        - DOCKER_BUILDKIT=1
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - .:/app
