name: Deploy to Production

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: [self-hosted]
    steps:
    - uses: actions/checkout@v3
    - name: Docker Compose
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        SERPAPI_API_KEY: ${{ secrets.SERPAPI_API_KEY }}
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        API_URL: ${{ secrets.API_URL }}

      run: docker compose up -d --force-recreate --build