name: Deploy to Production

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: [self-hosted]
    steps:
    - uses: actions/checkout@v3
    - name: Docker Compose
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: docker compose up -d --force-recreate --build